#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : damageproto
Version  : 1.2.1
Release  : 8
URL      : http://xorg.freedesktop.org/releases/individual/proto/damageproto-1.2.1.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/damageproto-1.2.1.tar.bz2
Summary  : Damage extension headers
Group    : Development/Tools
License  : HPND
Requires: damageproto-doc
BuildRequires : pkgconfig(xorg-macros)

%description
Damage
X Damage Extension
Version 1.1
2007-01-08
This package contains header files and documentation for the X Damage
extension.  Library and server implementations are separate.

%package dev
Summary: dev components for the damageproto package.
Group: Development
Provides: damageproto-devel

%description dev
dev components for the damageproto package.


%package doc
Summary: doc components for the damageproto package.
Group: Documentation

%description doc
doc components for the damageproto package.


%prep
%setup -q -n damageproto-1.2.1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/damageproto.h
/usr/include/X11/extensions/damagewire.h
/usr/lib64/pkgconfig/damageproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/damageproto/*
